### ISSUE TITLE
Multiple Embeds

### ISSUE THREAD

**Issue by hellomathew** [distantnative/embed#80]
Would be so rad to have a "+" icon that opens another input/URL field for multiple embeds

**Comment by distantnative** [comment]
You mean in the panel field? But then what would happen in your opinion if you do `<?= $page->yourembedfield() ?>` in a template?

**Comment by hellomathew** [comment]
In this case, I guess there'd have to be a way in the template to handle an array, "foreach" style?

**Comment by distantnative** [comment]
Thought about it, but I think the additional value is not worth the complexity it adds (implementing adding infinitely number of embed fields, handling of whether only one is saved or multiple...).

I feel that your wish is already fulfilled quite well using the embed field in a structure field:
```
  videos:
    label: Embeds
    type:  structure
    modalsize: large
    fields:
      video:
        label: Embed
        type: embed
```

And in your template you could then:
```php
<?php 
foreach($page->videos()->toStructure() as $embed) {
  echo $embed->video()->embed();
}
?>
```
